loans/urls.py
from django.conf.urls.defaults import *

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
	# Uncomment the admin/doc line below to enable admin documentation:
	(r'^admin/doc/', include('django.contrib.admindocs.urls')),

	# Uncomment the next line to enable the admin:
	(r'^admin/', include(admin.site.urls)),

	# (r'^accounts/login/$', 'django.contrib.auth.views.login', {'template_name':'accounts/login.html'}),
	# (r'^accounts/logout/$', 'django.contrib.auth.views.logout_then_login'),
	# (r'^accounts/logout/$', 'loans.views.logout_view'),
)

urlpatterns += patterns('loans.views',
	(r'^$', 'home'),
	(r'^loans/$', 'loans'),
	(r'^loans/(?P<loan_id>\d+)/$', 'loan_detail'),
	(r'^loans/(?P<loan_id>\d+)/lend$', 'lend_form'),
	(r'^accounts/login/$', 'login_view'),
	(r'^accounts/logout/$', 'logout_view'),
	(r'^accounts/profile/$', 'user_profile'),
)

urls.py
from django.conf.urls.defaults import *

urlpatterns = patterns('',
	(r'^', include('loans.urls')),
)

loans/models.py
# This is an auto-generated Django model module.
# You'll have to do the following manually to clean this up:
#	  * Rearrange models' order
#	  * Make sure each model has one field with primary_key=True
# Feel free to rename the models, but don't rename db_table values or field names.
#
# Also note: You'll have to insert the output of 'django-admin.py sqlcustom [appname]'
# into your database.

from django.db import models
from django.contrib.auth.models import User

class MyModel(models.Model):
	''' Convenience methods for all models '''
	class Meta:
		abstract = True

	def __unicode__(self):
		''' If model has a 'name' attribute, return that, else return model name + ID '''
		if 'name' in self.__dict__:
			return unicode(self.name)
		else:
			return unicode(self._meta.verbose_name.capitalize()) + ' ' + unicode(self.id)

	def get_translation(self, column_name, language_code='EN'):
		return get_translation(self._meta.db_table, column_name, self.id, language_code)


class Currency(MyModel):
	id = models.AutoField(primary_key=True, db_column='ID')
	name = models.CharField(max_length=150, db_column='Name')
	symbol = models.CharField(max_length=60, db_column='Symbol')
	description = models.TextField(db_column='Description')
	default_currency = models.IntegerField(db_column='DefaultCurrency')
	country = models.CharField(max_length=765, db_column='Country')
	exchange_rate = models.FloatField(db_column='ExchangeRate')
	class Meta:
		db_table = u'Currencies'
		verbose_name_plural = 'currencies'
	def __unicode__(self):
		return unicode(self.symbol)

class Division(MyModel):
	id = models.AutoField(primary_key=True, db_column='ID')
	name = models.CharField(max_length=765, db_column='Name')
	external_name = models.CharField(max_length=765, db_column='ExternalName', blank=True)
	account_division = models.ForeignKey('self', db_column='AccountDivision')
	super_division = models.ForeignKey('self', related_name='subdivision', null=True, db_column='SuperDivision', blank=True)
	country = models.CharField(max_length=360, db_column='Country')
	description = models.TextField(db_column='Description')
	class Meta:
		db_table = u'Divisions'

class Member(MyModel):
	id = models.AutoField(primary_key=True, db_column='ID')
	first_name = models.CharField(max_length=450, db_column='FirstName')
	last_name = models.CharField(max_length=450, db_column='LastName', blank=True)
	username = models.CharField(max_length=300, db_column='Username', blank=True)
	password = models.CharField(max_length=300, db_column='Password', blank=True)
	passcode = models.CharField(max_length=300, db_column='Passcode', blank=True)
	access_status = models.IntegerField(null=True, db_column='AccessStatus', blank=True)
	national_id = models.CharField(max_length=105, db_column='NationalID', blank=True)
	address = models.TextField(db_column='Address', blank=True)
	city = models.CharField(max_length=600, db_column='City', blank=True)
	country = models.CharField(max_length=600, db_column='Country', blank=True)
	phone = models.CharField(max_length=150, db_column='Phone', blank=True)
	mobile = models.CharField(max_length=180, blank=True)
	cooperative_id = models.IntegerField(null=True, db_column='CooperativeID', blank=True)
	birth_date = models.DateTimeField(null=True, db_column='BirthDate', blank=True)
	payroll = models.IntegerField(db_column='Payroll')
	class Meta:
		db_table = u'Members'
		ordering = ['first_name']
	def __unicode__(self):
		return unicode(self.first_name) + u' ' + unicode(self.last_name)

class AccountClass(MyModel):
	id = models.AutoField(primary_key=True, db_column='ID')
	class_id = models.CharField(max_length=765, db_column='ClassID')
	super_class = models.ForeignKey('self', max_length=765, db_column='SuperClassID', blank=True)
	name = models.CharField(max_length=765, db_column='Name')
	nombre = models.CharField(max_length=765, db_column='Nombre')
	description = models.TextField(db_column='Description', blank=True)
	class Meta:
		db_table = u'AccountClasses'
		verbose_name_plural = "account classes"

class AccountType(MyModel):
	id = models.AutoField(primary_key=True, db_column='ID')
	name = models.CharField(max_length=150, db_column='Name')
	description = models.TextField(db_column='Description')
	class Meta:
		db_table = u'AccountTypes'

class Account(MyModel):
	id = models.AutoField(primary_key=True, db_column='ID')
	external_accounting_id = models.CharField(unique=True, max_length=45, db_column='ExternalAccountingID', blank=True)
	name = models.CharField(unique=True, max_length=255, db_column='Name')
	nombre = models.CharField(max_length=765, db_column='Nombre')
	external_accounting_name = models.CharField(max_length=765, db_column='ExternalAccountingName', blank=True)
	division = models.ForeignKey(Division, db_column='DivisionID')
	currency = models.ForeignKey(Currency, db_column='Currency')
	description = models.TextField(db_column='Description')
	type = models.ForeignKey(AccountType, db_column='Type')
	external_party = models.IntegerField(null=True, db_column='ExternalParty', blank=True)
	class Meta:
		db_table = u'Accounts'

class BasicProject(MyModel):
	id = models.AutoField(primary_key=True, db_column='ID')
	type = models.CharField(max_length=90, db_column='Type')
	length = models.FloatField(db_column='Length')
	nivel = models.CharField(max_length=600, db_column='Nivel')
	coordinator = models.IntegerField(null=True, db_column='Coordinator', blank=True)
	assistant = models.IntegerField(null=True, db_column='Assistant', blank=True)
	goal = models.IntegerField(null=True, db_column='Goal', blank=True)
	start_date = models.DateTimeField(null=True, db_column='StartDate', blank=True)
	name = models.CharField(max_length=765, db_column='Name')
	short_description = models.TextField(db_column='ShortDescription')
	description = models.TextField(db_column='Description', blank=True)
	class Meta:
		db_table = u'BasicProjects'
	def __unicode__(self):
		return 'Basic Project '+unicode(self.name)

class Blog(MyModel):
	id = models.AutoField(primary_key=True, db_column='ID')
	title = models.CharField(max_length=765, db_column='Title')
	text = models.TextField(db_column='Text')
	type = models.CharField(max_length=765, db_column='Type')
	date = models.DateTimeField(db_column='Date')
	class Meta:
		db_table = u'Blog'

class Check(MyModel):
	id = models.AutoField(primary_key=True, db_column='ID')
	banco = models.CharField(max_length=600, db_column='Banco')
	numero_de_cheque = models.CharField(max_length=150, db_column='NumeroDeCheque')
	account_holder = models.CharField(max_length=765, db_column='AccountHolder')
	amount = models.FloatField(db_column='Amount')
	loan_id = models.IntegerField(db_column='LoanID')
	date_entered = models.DateField(db_column='DateEntered')
	date_due = models.DateField(db_column='DateDue')
	date_removed = models.DateField(null=True, db_column='DateRemoved', blank=True)
	date_bounced = models.DateField(null=True, db_column='DateBounced', blank=True)
	exidente = models.FloatField(null=True, db_column='Exidente', blank=True)
	gastos_financieros = models.FloatField(null=True, db_column='GastosFinancieros', blank=True)
	impuesto = models.FloatField(null=True, db_column='Impuesto', blank=True)
	bounced = models.IntegerField(null=True, db_column='Bounced', blank=True)
	notes = models.TextField(db_column='Notes', blank=True)
	class Meta:
		db_table = u'Checks'

class Cooperative(MyModel):
	id = models.AutoField(primary_key=True, db_column='ID')
	la_base_fund_account_id = models.IntegerField(null=True, db_column='LaBaseFundAccountID', blank=True)
	red_tekufen_fund_account_id = models.IntegerField(null=True, db_column='RedTekufenFundAccountID', blank=True)
	name = models.CharField(max_length=750, db_column='Name')
	alias = models.CharField(max_length=600, db_column='Alias', blank=True)
	address = models.TextField(db_column='Address', blank=True)
	city = models.CharField(max_length=600, db_column='City')
	country = models.CharField(max_length=600, db_column='Country')
	web = models.CharField(max_length=765)
	contact = models.TextField(db_column='Contact', blank=True)
	ownership = models.CharField(max_length=750, db_column='Ownership', blank=True)
	ownership_change_date = models.DateTimeField(null=True, db_column='OwnershipChangeDate', blank=True)
	recuperada = models.IntegerField(db_column='Recuperada')
	sector = models.CharField(max_length=600, db_column='Sector', blank=True)
	industry = models.CharField(max_length=600, db_column='Industry', blank=True)
	source = models.CharField(max_length=750, db_column='Source', blank=True)
	# thumb_path = MediaManager()
	class Meta:
		db_table = u'Cooperatives'
		ordering = ['name']

	# def picture_path(self):
	# 	return get_picture_path('Cooperatives', self.id)
	# picture_path = property(picture_path)
	# def thumb_path(self):
	# 	return get_thumb_path('Cooperatives', self.id)
	# thumb_path = property(thumb_path)

class ExchangeRate(MyModel):
	id = models.AutoField(primary_key=True, db_column='ID')
	currency_id = models.IntegerField(db_column='CurrencyID')
	exchange_rate = models.FloatField(db_column='ExchangeRate')
	date_start = models.DateField(db_column='DateStart')
	date_end = models.DateField(db_column='DateEnd')
	class Meta:
		db_table = u'ExchangeRates'

class Goal(MyModel):
	id = models.AutoField(primary_key=True, db_column='ID')
	name = models.CharField(max_length=150, db_column='Name')
	description = models.TextField(db_column='Description')
	date_activated = models.DateField(db_column='DateActivated')
	date_disactivated = models.DateField(null=True, db_column='DateDisactivated', blank=True)
	super_goal = models.IntegerField(null=True, db_column='SuperGoal', blank=True)
	class Meta:
		db_table = u'Goals'

class GroupTransactionID(MyModel):
	id = models.AutoField(primary_key=True, db_column='ID')
	starter_transaction = models.IntegerField(null=True, db_column='StarterTransaction', blank=True)
	date_created = models.DateTimeField(db_column='DateCreated')
	class Meta:
		db_table = u'GroupTransactionIDs'

loans/views.py
from django.shortcuts import render_to_response, get_object_or_404, redirect, render
from django.http import Http404, HttpResponseRedirect
# from django.db import connection
# from django.db.models import Q
from django.contrib import messages
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.views import login
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from loans.models import *
from loans.forms import *

def home(request):
	return render(request, 'home.html')
	
def loans(request):
	loans = Loan.objects.filter(nivel__in=['Prestamo Activo','Prestamo Completo']).order_by('-signing_date')[:10]

	for l in loans:
		l.short_description = l.get_short_description(language_code='EN')
		l.description = l.get_description(language_code='EN')
		l.thumb_path = l.picture_paths().get('thumb')
		# l.queries = connection.queries

	return render(request, 'loans/loans.html', {'loans': loans})
	
def loan_detail(request, loan_id):
	l = get_object_or_404(Loan, pk=loan_id)
	l.short_description = l.get_short_description(language_code='EN')
	l.description = l.get_description(language_code='EN')	
	l.picture_path = l.picture_paths().get('medium')
	l.pasos = []
	for paso in l.get_pasos():
		# if paso.finalized > 0: paso.finished_un = 'finished'
		# else: paso.finished_un = 'unfinished'
		if paso.completed: paso.is_completed = 'completed'
		else: paso.is_completed = 'not_completed'
		paso.summary = paso.get_translation('Summary', language_code='EN') or paso.summary
		paso.details = paso.get_translation('Details', language_code='EN') or paso.details
		paso.logs = []
		for log in paso.projectlog_set.all():
			log.explanation = log.get_translation('Explanation', language_code='EN')
			log.detailed_explanation = log.get_translation('DetailedExplanation', language_code='EN')
			paso.logs.append(log)
		l.pasos.append(paso)
	return render(request, 'loans/loan_detail.html', {'loan': l})

@login_required
def user_profile(request):
	user_account = UserAccount.objects.get_or_create(user=request.user)[0]
	# users_loans = user_account.loans.all()
	
	user_loan_contributions = UserLoanContribution.objects.filter(user_account=user_account)
	users_loans = []
	for ulc in user_loan_contributions:
		ulc.loan.thumb_path = ulc.loan.picture_paths().get('thumb')
		users_loans.append((ulc, ulc.loan))
	
	return render(request, 'accounts/profile.html', 
		{'user': request.user, 'account': user_account, 'users_loans': users_loans})

def logout_view(request):
	logout(request)
	messages.success(request, 'You have been logged out.')
	return redirect('loans.views.login_view')

# from django.dispatch import receiver
# from django.contrib.auth.signals import user_logged_in
# @receiver(user_logged_in)
# def myreceiver(sender, **kwargs):
# 	messages.debug(kwargs['request'], kwargs['user'].username+' logged in')

def login_view(request):
	''' Contains both a login form and a new user registration form. '''
	
	# Login form
	if request.method == 'POST' and request.POST['submit'] == 'Login': # If the login form has been submitted
		lform = LoginForm(request.POST)
		if lform.is_valid():
			d = lform.cleaned_data
			user = authenticate(username=d['username'], password=d['password'])
			login(request, user)
			return redirect('loans.views.user_profile')
	else:
		lform = LoginForm()

	# New user registration form
	if request.method == 'POST' and request.POST['submit'] == 'Sign Up': # If the new user form has been submitted
		newform = NewUserForm(request.POST)
		if newform.is_valid():
			d = newform.cleaned_data
			user = User.objects.create_user(
				d['username'],
				d['email'],
				d['password1']
			)
			# user = newform.save(commit=False)
			user.first_name = d['first_name']
			user.last_name = d['last_name']
			# user.email = d['email']
			user.save()
			user = authenticate(username=d['username'], password=d['password1'])
			login(request, user)
			# messages.debug(request, u.__dict__)
			return redirect('loans.views.user_profile')
	else:
		newform = NewUserForm()
	
	# Render page with both forms
	return render(request, 'accounts/login.html', {'newform': newform, 'lform': lform})

@login_required
def lend_form(request, loan_id):
	l = get_object_or_404(Loan, pk=loan_id)
	l.picture_path = l.picture_paths().get('medium')
	if request.method == 'POST': # If the form has been submitted...
		form = LendForm(request.POST)
		if form.is_valid(): # All validation rules pass
			amount = form.cleaned_data['amount']
			other_amount = form.cleaned_data['other_amount']
			if amount == 0:
				amount = other_amount
			u = UserAccount.objects.get(user=request.user)
			c = UserLoanContribution(
				user_account = u,
				loan = l,
				amount = amount,
				balance = amount,
			)
			c.save()
			u.balance -= amount
			u.save()
			messages.success(request, 'Thank you! Your loan has been made.')
			return redirect('loans.views.user_profile') # Redirect after POST
	else:
		form = LendForm()
	
	return render(request, 'loans/lend_form.html', {'form': form, 'loan': l})

loans/templates/loans/lend_form.html
{% extends "base.html" %}
{% load url from future %}

{% block title %}{{ loan }}: Lend{% endblock %}

{% block head %}
<script>
	function show_hide_other(speed) {
		if (!speed) speed = 'fast'
		amount = $('#id_amount').val()
		if (amount == "0") 
			$('#div_other_amount').show(speed)
		else $('#div_other_amount').hide(speed)
	}
	$(document).ready(function() {
		show_hide_other('')
	})
</script>
{% endblock %}

{% block content %}
<div class="span_6">
    <div class="row">
<h1>{{ loan }}: Lend</h1>

{% if loan.picture_path %}
	<div class="picture">
		<img src="http://www.theworkingworld.org/{{ loan.picture_path }}" alt="{{ loan }}">
	</div>
{% endif %}
<div class="short_description">
	{{ loan.short_description|default:'' }}
</div>
 </div><!-- /.row -->
</div><!-- /.span_6 -->
<div class="span_6">
     <div class="row">
<div class="lend_form">
	{# <ul class="errorlist"> #}
	{# 	{% for key, value in form.errors %} #}
	{# 		<li>{{key}}: {{ value }}</li> #}
	{# 	{% endfor %} #}
	{# </ul> #}
	{# {% if form.form_errors %}<p class="error_message"><strong>{{ form.form_errors }}</strong></p>{% endif %} #}
	<form method="post" action="{% url 'loans.views.lend_form' loan.id %}">
		{% csrf_token %}
		{{ form.amount.errors }}
		{{ form.other_amount.errors }}
		<div id="div_amount">
			{{ form.amount.label_tag }}: 
			{{ form.amount }}
		</div>
		<div id="div_other_amount">
			{{ form.other_amount.label_tag }}:
			{{ form.other_amount }}
		</div>
		<input type="submit" class="btn btn-primary" value="Lend">
	</form>
</div><!-- /.lend_form -->
      </div><!-- /.row -->
    </div><!-- /.span_6 -->
{% endblock %}

loans/templates/loans/loan_detail.html
{% extends "base.html" %}
{% load url from future %}

{% block title %}{{ loan }}{% endblock %}

{% block content %}
<div class="pull-right"><a class="btn btn-link" href="{% url 'loans.views.loans' %}">&lt; Back to Loan List</a></div>
<div class="span_12">
      <div class="row">
<h1>{{ loan }}</h1>

{% if loan.picture_path %}
	<div class="picture img-polaroid">
		<img src="http://www.theworkingworld.org/{{ loan.picture_path }}" alt="{{ loan }}">
	</div>
{% endif %}
<div class="short_description">
	{{ loan.short_description|default:'' }}
</div>
<div class="description">
	<h3>Details</h3>
	{{ loan.description|default:'<span style="font-style:italic;" class="notfound">No description found.</span>' }}
</div>
<div class="lend">
	<a class="button lend_button btn" href="{% url 'loans.views.lend_form' loan.id %}">Lend</a>
</div>
<div class="loan_calendar">
	<h3>Calendar</h3>
	<ul>
		{% for paso in loan.pasos %}
		<li class="paso {{ paso.is_completed }}">
			Milestone {{ paso.date }}: {{ paso.summary }}
			{% if paso.completed %}
			(Completed {{ paso.completed }})
			{% else %}
			(Not yet completed)
			{% endif %}
			{% if paso.details %}<br>Details: {{ paso.details }}{% endif %}
			<ul>
				{% for log in paso.logs %}
				<li class="log">Log {{ log.date }}: {{ log.explanation }}
					<ul>
						<li>Progress: {{ log.progress }}</li>
						<li>Details: {{ log.detailed_explanation }}</li>
					</ul>
				</li>
				{% endfor %}
			</ul>
		</li>
		{% endfor %}
	</ul>
</div>
    </div><!-- /.row -->
  </div><!-- /.span_12 -->
{% endblock content %}

loans/templates/loans/loans.html
{% extends "base.html" %}
{% load url from future %}

{% block title %}Loans{% endblock %}

{% block content %}

{% if loans %}

<div class="span_12">
	<div class="row clearfix">
		<ul>
		{% for loan in loans %}
				<li class="loan clearfix">
					<div class="pic img-polaroid">
						{% if loan.thumb_path %}
							<p><a href="{% url 'loans.views.loan_detail' loan.id %}">
								<img src="http://www.theworkingworld.org/{{ loan.thumb_path }}" alt="{{ loan.cooperative }}">
							</a></p>
						{% endif %}
					</div>
					<div class="desc">
						<p><a href="{% url 'loans.views.loan_detail' loan.id %}">Project with {{ loan.cooperative }}</a><br>
						{{ loan.short_description }}</p>
					</div>
					<div class="facts">
						<p>{{ loan.signing_date }}<br>
						{{ loan.amount_formatted }}</p>
					</div>
				</li>
		{% endfor %}
		</ul>
	</div><!-- /.row -->
</div><!-- /.span_12 -->

{% else %}
		<p>No loans found.</p>
{% endif %}

{% endblock content %}